### ISSUE TITLE
miss hparams.yaml for inference

### ISSUE THREAD

**Issue by nukes** [karnwatcharasupat/bandit#3]
Hi， it seems that you did not upload the hparams.yaml for inference:
```bash
(py3.10) python inference.py inference \                                                                                          [16:51:26]
  --ckpt_path=model/dnr-bsrnn-gru8-vox7-l1-effects.ckpt \
  --file_path=/soundx_speech_data/eval_audio/【走心短片】老师，你好！_01.wav \
  --model_name=test_model
/data1/martinzheng/miniconda3/envs/py3.10/lib/python3.10/site-packages/torch_audiomentations/utils/io.py:27: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")
Traceback (most recent call last):
  File "/data1/martinzheng/tts/backend/bandit/inference.py", line 281, in <module>
    fire.Fire()
  File "/data1/martinzheng/miniconda3/envs/py3.10/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/data1/martinzheng/miniconda3/envs/py3.10/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/data1/martinzheng/miniconda3/envs/py3.10/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/data1/martinzheng/tts/backend/bandit/inference.py", line 44, in inference
    config: Dict = read_nested_yaml(os.path.join(ckpt_dir, "hparams.yaml"))
  File "/data1/martinzheng/tts/backend/bandit/utils/config.py", line 47, in read_nested_yaml
    config = read_yaml(path)
  File "/data1/martinzheng/tts/backend/bandit/utils/config.py", line 12, in read_yaml
    with open(path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'hparams.yaml'
```

**Comment by kwatcharasupat** [comment]
Please get the relevant config file from the `expt` folder and place them in the same folder as the checkpoint.

**Comment by youngandbin** [comment]
@kwatcharasupat  Hi, I placed the config file in the same folder as the checkpoint and renamed it as hparams.yaml. However, I got the following error when I tried with `dnr-3s-bark48-l1snr.ckpt`, `dnr-3s-erb48-l1snr.ckpt`, `dnr-3s-erb64-l1snr.ckpt`. Can you help?

```
Traceback (most recent call last):
  File "/home/elicer/workspace/STT/bandit/inference.py", line 282, in <module>
    fire.Fire()
  File "/home/elicer/workspace/STT/bandit/.venv/lib/python3.10/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/elicer/workspace/STT/bandit/.venv/lib/python3.10/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/elicer/workspace/STT/bandit/.venv/lib/python3.10/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/elicer/workspace/STT/bandit/inference.py", line 122, in inference
    model.predict_step(
  File "/home/elicer/workspace/STT/bandit/core/__init__.py", line 537, in predict_step
    batch, output = self.predtest_step(batch, batch_idx, dataloader_idx)
  File "/home/elicer/workspace/STT/bandit/core/__init__.py", line 448, in predtest_step
    output = self.fader(
  File "/home/elicer/workspace/STT/bandit/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/elicer/workspace/STT/bandit/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/elicer/workspace/STT/bandit/core/utils/audio.py", line 205, in forward
    padded_audio, n_chunks = self.prepare(audio)
  File "/home/elicer/workspace/STT/bandit/core/utils/audio.py", line 179, in prepare
    audio = F.pad(audio, self.edge_frame_pad_sizes, mode="reflect")
  File "/home/elicer/workspace/STT/bandit/.venv/lib/python3.10/site-packages/torch/nn/functional.py", line 5096, in pad
    return torch._C._nn.pad(input, pad, mode, value)
RuntimeError: Argument #4: Padding size should be less than the corresponding input dimension, but got: padding (485100, 485100) at dimension 2 of input [2, 1, 440687]
```
